### ISSUE TITLE
Lack of customization

### ISSUE THREAD

**Issue by PEMapModder** [PMPlugins/PluginGenerator#1]
This generator has no customization at all. It can only be regarded as a plugin **template**, not a plugin **generator**.

**Comment by jojoe77777** [comment]
I guess it's a plugin template generator...? @legoboy0215?

**Comment by legoboy0215** [comment]
This is a start... Sorry since I made it in my school library as my friend told me I am bad at coding :P
Even I indeed am. :)

**Comment by legoboy0215** [comment]
I think make a web page? But I don't know how to make those fancy folders…

**Comment by PEMapModder** [comment]
What fancy folders?

**Comment by PEMapModder** [comment]
https://github.com/PEMapModder/plugingen-source
If you mean like the folders structure on GitHub and pmt.mcpe.me where you can read through multiple directories that only have one subdirectory in them, that requires pretty complicated recursive coding skills. Have fun with it :smile:

**Comment by legoboy0215** [comment]
... Yeah.. As you said before, if multiple users use the webpage I will have to create folders to package into  phar for download. OMG…

**Comment by PEMapModder** [comment]
actually, the plugin generator website does not generate any files except temp files for phar files (but not folders). I used `addFromString`, so I don't need to create files.

**Comment by legoboy0215** [comment]
Can you show me that part? I finished the html only for now...

**Comment by PEMapModder** [comment]
Actually, if you want to help, you can create pull requests on my repo. I have working framework, but I am not good at HTML frontend, especially when it comes to designing.

**Comment by legoboy0215** [comment]
? I only do simple html. I saw your fie and it looks fine.
